name: Publish Version
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm install
      - name: Check version
        run: npm run check-version
        id: check-version
      - name: "publish package"
        # We only want to publish to npm if we have a new
        # version of this package.
        if: steps.check-version.outputs.isNewVersion == 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
