name: Test Workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm install
      - name: check-version
        uses: twilioquest/twilioquest-base/actions/check-version
      - run: echo "isNewVersion -> ${{steps.check-version.outputs.isNewVersion}}"
